logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-} spanId=%X{spanId:-}]"
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://781e58f79860b15642b66839f4d482af@o4511332810555393.ingest.de.sentry.io/4511332812652624
  send-default-pii: true
  traces-sample-rate: 1.0